### ISSUE TITLE
imgui control problem

### ISSUE THREAD

**Issue by mingyEx** [planetchili/hw3d#7]
Hello, have you fixed the problem that the imgui control is dislocated when the window enters full screen mode? I once asked this question in the discord channel and you said you would fix him.
But the discord channel has so many messages that I can't read them all
![image](https://user-images.githubusercontent.com/40135358/181175293-b4d84693-d420-449a-ad81-9f9d7bbbd9f4.png)
Like this, when I enter fullscreen mode, the slider can be manipulated effectively only if the mouse is in the red position

**Comment by SimbaScorpio** [comment]
您的邮件已接收

**Comment by SimbaScorpio** [comment]
您的邮件已接收
